DROP PROCEDURE TERCER_IMPACTO.CREAR_PROFESIONALES
DROP PROCEDURE TERCER_IMPACTO.CREAR_TIPO_Y_ESPECIALIDAD
DROP PROCEDURE TERCER_IMPACTO.CREAR_DIA_PROFESIONAL_DIA
DROP PROCEDURE TERCER_IMPACTO.CREAR_PLAN_MEDICO
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_PLAN_MED
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_PROFESIONALES
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_ESPECIALIDADES_TIPOS
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_PROFESIONAL_ESPECIALIDAD
DROP PROCEDURE TERCER_IMPACTO.CREAR_ROL_USUA_FUNC
DROP PROCEDURE TERCER_IMPACTO.LLENAR_TABLA_ROL_FUNC

DROP PROCEDURE TERCER_IMPACTO.MIGRAR_USUARIOS
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_TURNO
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_CONSULTA
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_BONO
DROP PROCEDURE TERCER_IMPACTO.MIGRAR_AFILIADOS


DROP TABLE TERCER_IMPACTO.PROFESIONAL_DIA --NADA QUE MIGRAR
DROP TABLE TERCER_IMPACTO.DIA --NADA QUE MIGRAR
DROP TABLE TERCER_IMPACTO.PROFESIONAL_ESPECIALIDAD
DROP TABLE TERCER_IMPACTO.ESPECIALIDAD
DROP TABLE TERCER_IMPACTO.TIPO_ESPECIALIDAD
DROP TABLE TERCER_IMPACTO.PROFESIONAL
DROP TABLE TERCER_IMPACTO.PLAN_MEDICO
DROP TABLE TERCER_IMPACTO.ROL_FUNCIONALIDAD
DROP TABLE TERCER_IMPACTO.ROL_USUARIO
DROP TABLE TERCER_IMPACTO.ROL
DROP TABLE TERCER_IMPACTO.USUARIO
DROP TABLE TERCER_IMPACTO.FUNCIONALIDAD

DROP TABLE TERCER_IMPACTO.AFILIADO
DROP TABLE TERCER_IMPACTO.BONO
DROP TABLE TERCER_IMPACTO.COMPRA_BONO
DROP TABLE TERCER_IMPACTO.TURNO
DROP TABLE TERCER_IMPACTO.CONSULTA



DROP SCHEMA TERCER_IMPACTO

USE [GD2C2016]
GO

--CREACION DEL ESQUEMA NOMBRE DEL GRUPO--
CREATE SCHEMA [TERCER_IMPACTO] AUTHORIZATION [GD]
GO



CREATE PROCEDURE TERCER_IMPACTO.CREAR_PROFESIONALES
AS
BEGIN
	CREATE TABLE TERCER_IMPACTO.PROFESIONAL(
		MATRICULA NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(255),
		TIPO_DOC VARCHAR(20),
		NRO_DOC NUMERIC(18,0),
		DIRECCION VARCHAR(255),
		TELEFONO NUMERIC(18,0),
		MAIL VARCHAR(255),
		FECHA_NAC DATETIME,
		SEXO VARCHAR(1),
		APELLIDO VARCHAR(255)
	
	)
END
GO


CREATE PROCEDURE TERCER_IMPACTO.CREAR_AFILIADOS
AS
BEGIN
	CREATE TABLE TERCER_IMPACTO.AFILIADO(
		ID_AFILIADO NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(255),
		APELLIDO VARCHAR(255),
		TIPO_DOC VARCHAR(20),
		NRO_DOC NUMERIC(18,0),
		DIRECCION VARCHAR(255),
		TELEFONO NUMERIC(18,0),
		MAIL VARCHAR(255),
		FECHA_NAC DATETIME,
		SEXO VARCHAR(1),
		ESTADO_CIVIL VARCHAR(50),
		CANT_HIJOS NUMERIC(18,0),
		ID_MEDICO NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
        TERCER_IMPACTO.PROFESIONAL(MATRICULA),
	
	)
END
GO


CREATE PROCEDURE TERCER_IMPACTO.CREAR_TIPO_Y_ESPECIALIDAD
AS
BEGIN
	CREATE TABLE TERCER_IMPACTO.TIPO_ESPECIALIDAD(
		ID_TIPO_ESPECIALIDAD NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		DESCRIPCION VARCHAR(255)
		)

	CREATE TABLE TERCER_IMPACTO.ESPECIALIDAD(
		ID_ESPECIALIDAD NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		DESCRIPCION VARCHAR(255),
		TIPO_ESPECIALIDAD NUMERIC(18,0) FOREIGN KEY REFERENCES 
		TERCER_IMPACTO.TIPO_ESPECIALIDAD(ID_TIPO_ESPECIALIDAD)
		)
		
	CREATE TABLE TERCER_IMPACTO.PROFESIONAL_ESPECIALIDAD(
		ID_PROF_ESP NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		ID_PROFESIONAL NUMERIC(18,0) NOT NULL 
		FOREIGN KEY REFERENCES
		TERCER_IMPACTO.PROFESIONAL(MATRICULA),
		ID_ESPECIALIDAD NUMERIC(18,0) NOT NULL 
		FOREIGN KEY REFERENCES
		TERCER_IMPACTO.ESPECIALIDAD(ID_ESPECIALIDAD)
		)
END
GO

CREATE PROCEDURE TERCER_IMPACTO.CREAR_DIA_PROFESIONAL_DIA
AS
BEGIN
	CREATE TABLE TERCER_IMPACTO.DIA(
		ID_DIA NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		FECHA DATE NOT NULL)
		
	CREATE TABLE TERCER_IMPACTO.PROFESIONAL_DIA(
		
		ID_PROF_ESP NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
		TERCER_IMPACTO.PROFESIONAL_ESPECIALIDAD(ID_PROF_ESP),
		ID_DIA NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
		TERCER_IMPACTO.DIA(ID_DIA),
		COMIENZO TIME NOT NULL,
		FIN TIME NOT NULL,
		CONSTRAINT PROF_DIA_PK PRIMARY KEY (ID_PROF_ESP,
		ID_DIA)
		)

END
GO

CREATE PROCEDURE TERCER_IMPACTO.CREAR_PLAN_MEDICO
AS
BEGIN
	CREATE TABLE TERCER_IMPACTO.PLAN_MEDICO(
		ID_PLAN_MEDICO NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		DESCRIPCION VARCHAR(255),
		PRECIO_BONO_CONSULTA NUMERIC(18,0),
		PRECIO_BONO_FARMACIA NUMERIC(18,0) 
	)
END
GO

CREATE PROCEDURE TERCER_IMPACTO.CREAR_BONO

AS
BEGIN
	CREATE TABLE TERCER_IMPACTO.BONO(
		ID_BONO NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		ID_PLAN_MEDICO NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
        TERCER_IMPACTO.PLAN_MEDICO(ID_PLAN_MEDICO),
		ID_AFILIADO NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
		TERCER_IMPACTO.AFILIADO(ID_AFILIADO),
		ID_CONSULTA NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
        TERCER_IMPACTO.CONSULTA(ID_CONSULTA),
        FECHA DATE NOT NULL,
		)
	
	CREATE TABLE TERCER_IMPACTO.COMPRA_BONO(
		MONTO NUMERIC(18,0) 
		CANTIDAD_BONOS NUMERIC(18,0) 
		ID_AFILIADO NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
		TERCER_IMPACTO.AFILIADO(ID_AFILIADO),
		CONSTRAINT COMPRA_BONO_PK PRIMARY KEY (ID_AFILIADO)
		FECHA_COMPRA DATE NOT NULL,
		)
	
END
GO

--10
CREATE PROCEDURE TERCER_IMPACTO.CREAR_TURNO
AS
BEGIN
	CREATE TABLE TERCER_IMPACTO.TURNO(
		ID_TURNO NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		ID_MEDICO NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
        TERCER_IMPACTO.MEDICO(ID_MEDICO),
		ID_AFILIADO NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
        TERCER_IMPACTO.AFILIADO(ID_AFILIADO),
		FECHA DATE NOT NULL
		)


END
GO
--11
CREATE PROCEDURE TERCER_IMPACTO.CREAR_CONSULTA
AS
BEGIN
		
	CREATE TABLE TERCER_IMPACTO.CONSULTA(
		ID_CONSULTA NUMERIC(18,0) NOT NULL 
		ID_TURNO NUMERIC(18,0) NOT NULL FOREIGN KEY REFERENCES
		TERCER_IMPACTO.TURNO(ID_TURNO),
		SINTOMAS VARCHAR(255),
		DIAGNOSTICO VARCHAR(255)
		FECHA DATE NOT NULL
		CONSTRAINT CONSULTA_PK PRIMARY KEY (ID_CONSULTA, ID_TURNO),

END
GO


--SET IDENTITY INSERT NOMBRETABLA ON
--SET IDENTITY INSERT NOMBRETABLA OFF

CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_TURNO
AS
BEGIN
	SET IDENTITY_INSERT TERCER_IMPACTO.TURNO ON;
	INSERT INTO TERCER_IMPACTO.TURNO (ID_TURNO,
	FECHA)
	SELECT DISTINCT Turno_numero, Turno_fecha 
	FROM gd_esquema.Maestra WHERE Turno_numero IS NOT NULL
	SET IDENTITY_INSERT TERCER_IMPACTO.TURNO OFF;
END
GO

CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_CONSULTA
AS
BEGIN
	SET IDENTITY_INSERT TERCER_IMPACTO.CONSULTA ON;
	INSERT INTO TERCER_IMPACTO.CONSULTA (SINTOMAS,
	DIAGNOSTICO)
	SELECT DISTINCT Consulta_sintomas, Consulta_diagnostico 
	FROM gd_esquema.Maestra WHERE Consulta_sintomas IS NOT NULL
	SET IDENTITY_INSERT TERCER_IMPACTO.CONSULTA OFF;
END
GO

CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_BONO
AS
BEGIN
	SET IDENTITY_INSERT TERCER_IMPACTO.BONO ON;
	INSERT INTO TERCER_IMPACTO.BONO (ID_BONO, FECHA)
	SELECT DISTINCT Bono_Consulta_Numero, Bono_Consulta_Fecha_Impresion 
	FROM gd_esquema.Maestra WHERE Bono_Consulta_Numero IS NOT NULL
	SET IDENTITY_INSERT TERCER_IMPACTO.BONO OFF;	
END
GO

--
CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_AFILIADOS
AS
BEGIN

	INSERT INTO TERCER_IMPACTO.AFILIADO (NOMBRE, APELLIDO
	TIPO_DOC, NRO_DOC, DIRECCION,TELEFONO, MAIL, FECHA_NAC,
	)
	SELECT DISTINCT Paciente_Nombre, Paciente_Apellido, 'DNI',
	Paciente_Dni, Paciente_Direccion, Paciente_Telefono, Paciente_Mail, Paciente_Fecha_Nac
	FROM gd_esquema.Maestra WHERE Paciente_Dni IS NOT NULL
	
END
GO


CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_PLAN_MED
AS
BEGIN
	SET IDENTITY_INSERT TERCER_IMPACTO.PLAN_MEDICO ON;
	INSERT INTO TERCER_IMPACTO.PLAN_MEDICO (ID_PLAN_MEDICO,
	DESCRIPCION,PRECIO_BONO_CONSULTA,PRECIO_BONO_FARMACIA)
	SELECT DISTINCT PLAN_MED_CODIGO, Plan_Med_Descripcion,
	Plan_Med_Precio_Bono_Consulta, Plan_Med_Precio_Bono_Farmacia 
	FROM gd_esquema.Maestra WHERE Plan_Med_Codigo IS NOT NULL
	SET IDENTITY_INSERT TERCER_IMPACTO.PLAN_MEDICO OFF;
END
GO

CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_PROFESIONALES
AS
BEGIN
	INSERT INTO TERCER_IMPACTO.PROFESIONAL(NRO_DOC,NOMBRE,
	TIPO_DOC,DIRECCION,TELEFONO, MAIL, FECHA_NAC,
	APELLIDO) 
	SELECT DISTINCT Medico_Dni,Medico_Nombre,'DNI', Medico_Direccion,
	Medico_Telefono,Medico_Mail,Medico_Fecha_Nac,Medico_Apellido
	FROM gd_esquema.Maestra WHERE Medico_Dni IS NOT NULL
	--el sexo se agregara mas tarde	porque no estamos seguros de algunos sexos		

END
GO

CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_ESPECIALIDADES_TIPOS
AS
BEGIN

	SET IDENTITY_INSERT TERCER_IMPACTO.TIPO_ESPECIALIDAD ON;
	
	INSERT INTO TERCER_IMPACTO.TIPO_ESPECIALIDAD
	(ID_TIPO_ESPECIALIDAD,DESCRIPCION)
	SELECT DISTINCT Tipo_Especialidad_Codigo,Tipo_Especialidad_Descripcion 
	FROM gd_esquema.Maestra WHERE Tipo_Especialidad_Codigo IS NOT NULL;
	
	SET IDENTITY_INSERT TERCER_IMPACTO.TIPO_ESPECIALIDAD OFF;
	
	SET IDENTITY_INSERT TERCER_IMPACTO.ESPECIALIDAD ON;
	
	INSERT INTO TERCER_IMPACTO.ESPECIALIDAD
	(ID_ESPECIALIDAD,DESCRIPCION,TIPO_ESPECIALIDAD)
	SELECT DISTINCT Especialidad_Codigo,Especialidad_Descripcion,
	Tipo_Especialidad_Codigo

	FROM gd_esquema.Maestra WHERE Especialidad_Codigo IS NOT NULL
	
	SET IDENTITY_INSERT TERCER_IMPACTO.ESPECIALIDAD OFF;
	
END
GO

CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_PROFESIONAL_ESPECIALIDAD
AS
BEGIN
	INSERT INTO TERCER_IMPACTO.PROFESIONAL_ESPECIALIDAD
	(ID_PROFESIONAL,ID_ESPECIALIDAD)
	SELECT MATRICULA,Especialidad_Codigo  FROM
	TERCER_IMPACTO.PROFESIONAL AS PRO
	JOIN gd_esquema.Maestra AS MA
	ON MA.Medico_Dni=PRO.NRO_DOC
	GROUP BY MATRICULA, Especialidad_Codigo
	
END
GO

CREATE PROCEDURE TERCER_IMPACTO.CREAR_ROL_USUA_FUNC
AS
BEGIN

	CREATE TABLE TERCER_IMPACTO.FUNCIONALIDAD(
		ID_FUNC NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		DESCRIPCION VARCHAR(255) NOT NULL
		)
	
	CREATE TABLE TERCER_IMPACTO.ROL(
		ID_ROL NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NOMBRE VARCHAR(155) NOT NULL,
		HABILITADO BIT NOT NULL DEFAULT 1--0 FALSE 1 TRUE
		)
	
	CREATE TABLE TERCER_IMPACTO.USUARIO(
		ID_USUARIO NUMERIC(18,0) NOT NULL IDENTITY(1,1) PRIMARY KEY,
		PASS VARCHAR(255) NOT NULL,
		USERNAME VARCHAR(255) UNIQUE NOT NULL,
		INTENTOS_FALLIDOS INT DEFAULT 0 --MAS DE 2 IMPLICA INHABILITADO
		)
		
	CREATE TABLE TERCER_IMPACTO.ROL_FUNCIONALIDAD(
		ROL_ID NUMERIC(18,0) NOT NULL FOREIGN KEY
		REFERENCES TERCER_IMPACTO.ROL(ID_ROL),
		FUNC_ID NUMERIC(18,0) NOT NULL FOREIGN KEY
		REFERENCES TERCER_IMPACTO.FUNCIONALIDAD(ID_FUNC),
		CONSTRAINT ROL_FUNC_PK PRIMARY KEY (ROL_ID,FUNC_ID)
		)
		
	CREATE TABLE TERCER_IMPACTO.ROL_USUARIO(
		ROL_ID NUMERIC(18,0) NOT NULL FOREIGN KEY
		REFERENCES TERCER_IMPACTO.ROL(ID_ROL),
		USUARIO_ID NUMERIC(18,0) NOT NULL FOREIGN KEY
		REFERENCES TERCER_IMPACTO.USUARIO(ID_USUARIO),
		CONSTRAINT ROL_US_PK PRIMARY KEY (ROL_ID,USUARIO_ID)
		)


END
GO

CREATE PROCEDURE TERCER_IMPACTO.LLENAR_TABLA_ROL_FUNC
AS
BEGIN

	INSERT INTO TERCER_IMPACTO.ROL (NOMBRE)
	VALUES 
	('AFILIADO'),
	('ADMINISTRATIVO'),
	('PROFESIONAL')
	
	--ADMINISTRATIVO--
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('ABM ROL');
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('ABM USUARIO');--NO SE HACE
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('ABM AFILIADO');
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('ABM PROFESIONAL');--NO SE HACE
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('ABM ESPECIALIDAD');--NO SE HACE
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('ABM PLAN');--NO SE HACE
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('REGISTRAR LLEGADA');
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('LISTADO ESTADISTICO');
	--AFILIADO Y ADMINISTRATIVO
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('PEDIR TURNO');
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('COMPRAR BONOS');
	--PROFESIONAL
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('REGISTRAR AGENDA');
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('REGISTRAR DIAGNOSTICO');
	--AFILIADO Y PROFESIONAL
	INSERT INTO TERCER_IMPACTO.FUNCIONALIDAD VALUES ('CANCELAR TURNO'); --SON DISTINTAS
	--OJO, EL ADMINISTRATIVO NO TIENE CANCELAR TURNO
	
	INSERT INTO TERCER_IMPACTO.ROL_FUNCIONALIDAD (ROL_ID,FUNC_ID)
	SELECT R.ID_ROL,F.ID_FUNC 
	FROM TERCER_IMPACTO.ROL R CROSS JOIN
	TERCER_IMPACTO.FUNCIONALIDAD F WHERE R.NOMBRE='ADMINISTRATIVO'
	--AND F.DESCRIPCION <> 'REGISTRAR AGENDA' AND F.DESCRIPCION <> 'REGISTRAR DIAGNOSTICO'
	--AND F.DESCRIPCION <> 'CANCELAR TURNO'
	--ADMINISTRATIVO CON TODAS LAS FUNCIONALIDADES PARA CORREGIR EL TP
	
	INSERT INTO TERCER_IMPACTO.ROL_FUNCIONALIDAD (ROL_ID,FUNC_ID)
	SELECT R.ID_ROL,F.ID_FUNC 
	FROM TERCER_IMPACTO.ROL R CROSS JOIN
	TERCER_IMPACTO.FUNCIONALIDAD F WHERE R.NOMBRE='PROFESIONAL'
	AND (F.DESCRIPCION = 'REGISTRAR AGENDA' OR F.DESCRIPCION = 'REGISTRAR DIAGNOSTICO'
	OR F.DESCRIPCION = 'CANCELAR TURNO')
	
	INSERT INTO TERCER_IMPACTO.ROL_FUNCIONALIDAD (ROL_ID,FUNC_ID)
	SELECT R.ID_ROL,F.ID_FUNC 
	FROM TERCER_IMPACTO.ROL R CROSS JOIN
	TERCER_IMPACTO.FUNCIONALIDAD F WHERE R.NOMBRE='AFILIADO'
	AND (F.DESCRIPCION = 'PEDIR TURNO' OR F.DESCRIPCION = 'COMPRAR BONOS'
	OR F.DESCRIPCION = 'CANCELAR TURNO')
	
END
GO

--TRIGGER PARA EL PASSWORD DE USUARIO
CREATE TRIGGER TERCER_IMPACTO.TRIGGER_PASS on TERCER_IMPACTO.USUARIO
INSTEAD OF INSERT
AS
BEGIN
  INSERT INTO TERCER_IMPACTO.USUARIO (USERNAME,PASS)
       SELECT USERNAME,HASHBYTES ( 'SHA2_256',PASS )
       FROM inserted
END
GO

CREATE PROCEDURE TERCER_IMPACTO.MIGRAR_USUARIOS
AS BEGIN
	INSERT INTO TERCER_IMPACTO.USUARIO (USERNAME,PASS) 
	VALUES ('admin','w32e')
	
	INSERT INTO TERCER_IMPACTO.ROL_USUARIO (ROL_ID,USUARIO_ID)
	SELECT R.ID_ROL, U.ID_USUARIO FROM TERCER_IMPACTO.ROL R
	,TERCER_IMPACTO.USUARIO U WHERE U.USERNAME='admin'
	AND R.NOMBRE='ADMINISTRATIVO' 
	
	--FALTA MIGRAR LOS AFILIADOS Y LOS PROFESIONALES A LA TABLA USUARIOS
	--COMO PASS SE PUEDE PONER EL NOMBRE Y APELLIDO
	--Y PONERLE A CADA UNO SU ROL EN ROL_USUARIO

END



EXEC TERCER_IMPACTO.CREAR_PROFESIONALES;
EXEC TERCER_IMPACTO.CREAR_TIPO_Y_ESPECIALIDAD;
EXEC TERCER_IMPACTO.CREAR_DIA_PROFESIONAL_DIA;
EXEC TERCER_IMPACTO.CREAR_PLAN_MEDICO;

EXEC TERCER_IMPACTO.CREAR_AFILIADOS
EXEC TERCER_IMPACTO.CREAR_BONO
EXEC TERCER_IMPACTO.CREAR_TURNO
EXEC TERCER_IMPACTO.CREAR_CONSULTA

EXEC TERCER_IMPACTO.MIGRAR_PLAN_MED;
EXEC TERCER_IMPACTO.MIGRAR_PROFESIONALES;
EXEC TERCER_IMPACTO.MIGRAR_ESPECIALIDADES_TIPOS;
EXEC TERCER_IMPACTO.MIGRAR_PROFESIONAL_ESPECIALIDAD;
EXEC TERCER_IMPACTO.CREAR_ROL_USUA_FUNC
EXEC TERCER_IMPACTO.LLENAR_TABLA_ROL_FUNC
EXEC TERCER_IMPACTO.MIGRAR_USUARIOS

EXEC TERCER_IMPACTO.MIGRAR_TURNO
EXEC TERCER_IMPACTO.MIGRAR_CONSULTA
EXEC TERCER_IMPACTO.MIGRAR_BONO
EXEC TERCER_IMPACTO.MIGRAR_AFILIADOS

